---
- name: Set package version facts
  when: pdns_rec_package_version | length > 0
  block:
    - name: Prefix the version of the PowerDNS Recursor package with the correct separator on RedHat
      ansible.builtin.set_fact:
        _pdns_rec_package_version: -{{ pdns_rec_package_version }}
      when: ansible_os_family == 'RedHat'

    - name: Prefix the version of the PowerDNS Recursor package with the correct separator on Debian
      ansible.builtin.set_fact:
        _pdns_rec_package_version: ={{ pdns_rec_package_version }}
      when: ansible_os_family == 'Debian'

- name: Install the PowerDNS Recursor
  ansible.builtin.package:
    name: "{{ pdns_rec_package_name }}{{ _pdns_rec_package_version | default('') }}"
    state: present

- name: Install PowerDNS Recursor debug symbols
  ansible.builtin.package:
    name: "{{ pdns_rec_debug_symbols_package_name }}{{ _pdns_rec_package_version | default('') }}"
    state: present
  when: pdns_rec_install_debug_symbols_package

- name: Get version from binaries
  block:
    - name: Obtain pdns version string
      ansible.builtin.shell: |
        set -o pipefail
        {{ pdns_rec_bin_name }} --version 2>&1 | sed -n 's/.*PowerDNS Recursor \([0-9.]\+\).*/\1/p'
      args:
        executable: /bin/bash
      register: _pdns_rec_ver_output
      changed_when: false

    - name: Set pdns version
      ansible.builtin.set_fact:
        _pdns_rec_version: "{{ _pdns_rec_ver_output['stdout'] | regex_replace('-[.\\d\\w]+$', '') }}"
      when: not ansible_check_mode
