---
- name: Install python3-debian (required by deb822_repository)
  ansible.builtin.package:
    name: python3-debian
    state: present

- name: Add the PowerDNS Recursor APT Repository (Deb822-style)
  ansible.builtin.deb822_repository:
    name: "{{ pdns_rec_install_repo['name'] }}"
    types: deb
    uris: "https://{{ pdns_rec_install_repo['apt_repo_origin'] }}/{{ ansible_distribution | lower }}/"
    suites: "{{ ansible_distribution_release | lower }}-{{ pdns_rec_install_repo['apt_version'] }}"
    components: main
    architectures: "{{ _pdns_rec_apt_arch }}"
    signed_by: "{{ pdns_rec_install_repo['gpg_key'] }}"
  notify: update the apt cache

- name: Pin the PowerDNS Recursor APT Repository
  ansible.builtin.template:
    src: pdns-recursor.pin.j2
    dest: /etc/apt/preferences.d/pdns-recursor
    owner: root
    group: root
    mode: "0644"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
