---
on:
  push:
  pull_request:

jobs:
  Tests:
    name: Test role
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ansible:
          - "2.12"
          - "2.13"
          - "2.14"
        scenario:
          - pdns-rec-47
          - pdns-rec-48
          - pdns-rec-49
          - pdns-rec-50
          - pdns-rec-master
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run the tests
        run: tox -- molecule test -s ${{ matrix.scenario }}
        env:
          ANSIBLE: ${{ matrix.ansible }}
